# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79df6fc4d115855bfff32f0bf2346edf66c76340c460a73650e45a81175de63ae8b2c311e705ee6678e0d678ac676026fe0b2f5b660ddf627a086eebca691f1f

test:
  secret_key_base: e4b434ff217e2794daac67615d0dc00aa2a0d401d84873a59a360743d8026e38cfd009d608684c9576f5ce6108044999930edeef118dcdff08c927845a9df16c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
